Class {
	#name : 'FoliageTodo',
	#superclass : 'Object',
	#category : 'Foliage-Core-Todo',
	#package : 'Foliage-Core',
	#tag : 'Todo'
}

{ #category : 'as yet unclassified' }
FoliageTodo >> m001 [

	'extract site creation from publisher >> publish
	+ write some tests.
	'
]

{ #category : 'as yet unclassified' }
FoliageTodo >> m002 [

	' I want to get a FOPillarPage from 
		File @ /Users/ducasse/Test2/pharo-website/site/license.md
		using (aFOMicrodownReader file: file) model (ParserAndGenerateModelEntity) '
		
	+ 
	
	' We should do that for each of the kind of extensions because adfter we will do one for md2'
]
