"
Here are some random notes so that I understand something. 


```
FOPublisher commandLine activateWith: {
    'foliage'.
    'publish'.
    '--source'. '/home/esteban/dev/pharo/foliage/test/pharo-test-master/site'.
    '--target'. '/home/esteban/dev/pharo/foliage/test/'.
    '/home/esteban/dev/pharo/foliage/test/pharo-test-master/site/.foliage.ston' }.
```


Download 

```
http://github.com/pharo-project/pharo-website
```


"
Class {
	#name : 'FOWelcome',
	#superclass : 'Object',
	#instVars : [
		'website'
	],
	#category : 'Foliage-Core-Base',
	#package : 'Foliage-Core',
	#tag : 'Base'
}
