"
Besides fixing bugs and glitches here is a list of next tasks

- Checking the build process on github
   - staging?
- Generate publications based on citezen extension
  - should pass info as part of the configuration
  - the alternative if to pass it in file metadata but it means that we will have to duplicate it for virtual pages. In particular virtual page links can be placed in different page. so the information sohuld not be local
even if we should define an extension microdown to support <?thematicPage|key=KzTraits&title=Traits and more&A little explanation?>. The virtual page builder should have access to the build and all the information.


- Generate thematic publication pages extension
- Book gallery extension
- Schedule for ESUG like page
- What about a contents of the blog page?


"
Class {
	#name : 'F0DevTasks',
	#superclass : 'Object',
	#category : 'Foliage-DevTasks',
	#package : 'Foliage-DevTasks'
}
