"
Besides fixing bugs and glitches here is a list of next tasks

- Checking the build process on github
   - staging?
- Generate publications based on citezen extension
- Generate thematic publication pages extension
- Book gallery extension
- What about a contents of the blog page?


"
Class {
	#name : 'F0DevTasks',
	#superclass : 'Object',
	#category : 'Foliage-DevTasks',
	#package : 'Foliage-DevTasks'
}
