name: Build Foliage Artefact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Foliage
        run: ./scripts/build.sh
      - uses: actions/upload-artifact@v5
        with:
          name: foliage-runtime
          path: build/**
          retention-days: 5

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v5
      
      - name: Display structure of downloaded files
        run: ls -R artifacts      

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: **